apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u4d3vp9rd-python
  janus-idp.io/tekton: u4d3vp9rd-python
  backstage.io/kubernetes-id: u4d3vp9rd-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: u4d3vp9rd-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
