apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u4d3vp9rd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u4d3vp9rd-python 
  name: u4d3vp9rd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u4d3vp9rd-python 
