apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: u4d3vp9rd-python-gitops
  description: This is GitOps manifest for u4d3vp9rd-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=u4d3vp9rd-python
    backstage.io/kubernetes-id: u4d3vp9rd-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: u4d3vp9rd-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:u4d3vp9rd-python
