apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u4d3vp9rd-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:dd694b63217790dc4de0143dcf2cfe6a206cecfd@sha256:53abcbd143099f3d010e9cfa029bee5db23bc549aaf308bf8d67f9690d0ca373
          name: container-image
