apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u4d3vp9rd-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:e8a0403ad3ea55fe0f51dc6127b9219c9420dfd9@sha256:f6553d3f3eb8b4ab62c087e191d4638fcfc9d0b7c5cdb73b84c97077d682e3d7
          name: container-image
